apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models-rwx
  namespace: llm
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 500Gi
  # TODO: set to your RWX StorageClass (Longhorn RWX / CephFS / NFS / etc.)
  storageClassName: longhorn-rwx
